### ISSUE TITLE
Types don't work when using ESNext, NodeNext

### ISSUE THREAD

**Issue by Nedi11** [adamjkb/bark#78]
Typescript types don't work when using ESNext or NodeNext module resolution.

**Comment by adamjkb** [comment]
Hi,

Could you provide a minimum reproduction of the issue. Or package.json & jsconfig.json so there is a bit more to go on. 

Thanks!

**Comment by Nedi11** [comment]
> Hi,
> 
> Could you provide a minimum reproduction of the issue. Or package.json & jsconfig.json so there is a bit more to go on.
> 
> Thanks!

Here you go: https://codesandbox.io/p/devbox/red-snow-4qt6qv

**Comment by adamjkb** [comment]
<img width="1204" alt="image" src="https://github.com/adamjkb/bark/assets/32829904/1dafb7ae-292b-40a5-8346-67bc35b5cab5">

I downloaded the files from the sandbox and ran `npm install` and for me the types are showing up correctly. I noticed that you might be using yarn. I never used yarn but it seems possible that it somehow messes with typescript's module resolution and it has to run in cjs mode.

This library is fairly minimal and the apart from creating a cjs bundle is written in "vanilla" ESM. So it should be straight forward to modify the package.json in the node_modules folder. Let me know if you can make it work, I'm happy to accept a PR that would appease yarn.

(As a side note: I did base Bark's type strategy on [prisma extension accelerate](https://www.npmjs.com/package/@prisma/extension-accelerate?activeTab=code). So I would be curious if it works for that but not this what the difference is)

**Comment by Nedi11** [comment]
I am using NPM. types there show correctly but I meant for e.x in prisma.node.createRoot(), "createRoot()" doesn't show on prisma.node

**Comment by pincman** [comment]
> 我正在使用 NPM。我说的是 prisma.node.createRoot（） 中的 e.x，“createRoot（）”没有显示在 prisma.node 上我不是在谈论返回类型

+1
